name: Build and Release ARM NeoVIM Deb File
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 2 * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'run'
        required: false 
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Neovim Build Dependencies
        run: |
          mkdir /debs && sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y ninja-build gettext cmake unzip curl git file
          git clone --depth=1 https://github.com/neovim/neovim

      - name: Build Neovim for arm64
        run: |
          cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo ARCH=armhf
          cd build && cpack -G DEB --root-owner-group
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: neovim/build/nvim-linux64.deb
          tag_name: nvim-arm64